spring:
  data:
    redis:
      enabled: true
      host: localhost
      port: 6379

server:
  port: 8080
  shutdown: graceful

logging:
  level:
    io.kraluk.buildingproxy: DEBUG

management:
endpoints:
  endpoint:
    health:
      probes:
        enabled: false
  health:
    livenessstate:
      enabled: false
    readinessstate:
      enabled: false
  observations:
    annotations:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs

app:
  building:
    kontakt-client:
      base-url: http://127.0.0.1:8088
      api-key: "00000000-0000-0000-0000-000000000000"
    cache:
      enabled: true
      time-to-live: PT1M
