spring:
  application.name: building-proxy-tests

management:
  metrics:
    enable:
      tomcat: false
      jvm: false
      process: false
      hikaricp: false
      system: false
      jdbc: false
      http: false
      logback: false

logging:
  level:
    io.kraluk.buildingproxy: DEBUG

wiremock:
  server:
    files: classpath:/wiremock
    stubs: classpath:/wiremock/mappings
